// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import { FaInstagram, FaLinkedin, FaGithub } from "react-icons/fa";
import "./globals.css";
import Link from "next/link";
import Navigation from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app and a beginner in next js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background min-h-screen flex flex-col`}>
        {/* Header */}
        <header className="w-full py-8 px-6 font-Unbuntu relative">
          <Navigation />
        </header>

        {/* Main content */}
        <main className="flex-grow">
          {children}
        </main>

        {/* Footer */}
        <footer className="bg-footer w-full pb-6 pt-6 mt-auto">
          <div className="space-y-4">
            <div className="flex justify-center space-x-6">
              <Link href="#" className="text-white hover:text-gray-300 transition-colors">
                <FaInstagram />
              </Link>
              <Link href="#" className="text-white hover:text-gray-300 transition-colors">
                <FaGithub />
              </Link>
              <Link href="#" className="text-white hover:text-gray-300 transition-colors">
                <FaLinkedin />
              </Link>
            </div>

            <div className="flex justify-center">
              <ul className="flex flex-wrap justify-center gap-4 px-4 text-white font-Unbuntu">
                <li><Link href="#" className="hover:text-gray-300 transition-colors">Contact Me</Link></li>
                <li><Link href="#" className="hover:text-gray-300 transition-colors">My Services</Link></li>
                <li><Link href="#" className="hover:text-gray-300 transition-colors">Privacy Policy</Link></li>
                <li><Link href="#" className="hover:text-gray-300 transition-colors">Terms & Conditions</Link></li>
                <li><Link href="#" className="hover:text-gray-300 transition-colors">Career</Link></li>
              </ul>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}